apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/api_db"
            - name: RABBITMQ_URL
              value: "amqp://user:password@rabbitmq:5672/"

---

apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30082
      name: http
  selector:
    app: worker
